# Generated by Django 4.0.4 on 2022-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosduma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Video',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
