# Generated by Django 4.0.4 on 2022-04-25 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gosduma', '0002_posts_video_alter_posts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='Photo',
            field=models.ImageField(blank=True, default='notfoundwidth.png', null=True, upload_to='photos/posts/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Video',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Видео (не обязательно)'),
        ),
    ]
