# Generated by Django 4.0.4 on 2022-04-25 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gosduma', '0003_request_recipient_alter_posts_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gosduma.statuses', verbose_name='Статус'),
        ),
    ]
