# Generated by Django 4.0.4 on 2022-04-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gosduma', '0004_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='gosduma.statuses', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='RequestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Ответ')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.CharField(max_length=255)),
                ('answeron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gosduma.request', verbose_name='Запрос')),
            ],
        ),
    ]
