# Generated by Django 4.0.4 on 2022-04-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gosduma', '0005_alter_request_status_alter_request_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestanswer',
            options={'ordering': ['-id'], 'verbose_name': 'ответ', 'verbose_name_plural': 'ответы'},
        ),
    ]
