# Generated by Django 4.0.4 on 2022-04-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gosduma', '0006_alter_requestanswer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Photo',
            field=models.ImageField(blank=True, default='media/notfoundwidth.png', null=True, upload_to='photos/posts/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gosduma.statuses', verbose_name='Статус'),
        ),
    ]
