# Generated by Django 4.0.4 on 2022-04-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosduma', '0007_alter_posts_photo_alter_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('author', models.CharField(max_length=255, verbose_name='Кто')),
                ('log', models.CharField(max_length=255, verbose_name='Что сделал')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ['-id'],
            },
        ),
    ]
