# Generated by Django 4.0.4 on 2022-05-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosduma', '0008_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тэг сообщения')),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='Photo',
            field=models.ImageField(blank=True, default='notfoundwidth.png', null=True, upload_to='photos/posts/', verbose_name='Фото'),
        ),
    ]
