# Generated by Django 4.0.4 on 2022-05-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gosduma', '0009_tags_alter_posts_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['-id'], 'verbose_name': 'тэг', 'verbose_name_plural': 'тэги'},
        ),
        migrations.AddField(
            model_name='request',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gosduma.tags', verbose_name='Тэг'),
        ),
    ]
