# Generated by Django 4.0.4 on 2022-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosduma', '0011_request_file_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
