# Generated by Django 4.0.4 on 2022-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosduma', '0012_request_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='FIO',
            field=models.EmailField(max_length=254, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта для связи'),
        ),
    ]
